### ISSUE TITLE
Project Description and Feature Outline

### ISSUE THREAD

**Issue by rkett** [rkett/local-weather#1]
Taken from [FCC](https://www.freecodecamp.org/challenges/show-the-local-weather) project.
Amended by me.

# Purpose

Create a central area to outline and skeleton the entire project. Features and requirements are listed here, and their sub-issues are linked back. Discussion and outlines of each of these in-depth are given in their separate pages instead of here. Closing of this issue indicates that the first "production" ready version of this project has been completed.

## Features:

- [ ] Feature: I can see the weather in my current location see: https://github.com/rkett/local-weather/issues/2

- [ ] Feature: I can see a different icon or background image (e.g. snowy mountain, hot desert) depending on the weather see: https://github.com/rkett/local-weather/issues/3

- [ ] Feature: I can push a button to toggle between Fahrenheit and Celsius see:  https://github.com/rkett/local-weather/issues/4

## Major Requirements

- [ ] Accessibility: Mobile friendly.

- [ ] Accessibility: Semantically coded HTML.

- [ ] Code: CSS has reduced redundancy. 

## Minor Requirements

- [ ] Style is uniquely developed (current idea Left <> Right Layout: Text on right <> Symbol on Left)

- [ ] Smooth animations for all features.

- [ ] Incorporate one unique aspect of a TV show into design.
